const assert=require('node:assert/strict');
const {Game}=require('../src/engine.js');let checks=0;
const test=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
function prepared(spec='warrior',roll=.99){const g=new Game(()=>roll);g.reset();g.enterShop();g.enterBoss();g.boss.hp=1;g.hero.x=g.boss.x-25;g.hero.face=0;g.strike();assert(g.specialize('Vesper',spec));g.hero.x=330;g.hero.y=136;assert(g.openChest());return g;}
function chapter(spec='warrior',roll=.99){const g=prepared(spec,roll);assert(g.beginChapter2());return g;}
function walk(g,d){g.doorCooldown=0;assert(g.travel(d));}
function clear(g){while(g.enemies.length){const e=g.enemies[0];e.dormant=false;g.hero.x=200;g.hero.y=140;g.hero.face=0;e.x=220;e.y=140;g.cooldown=0;g.strike();if(g.hero.specialization!=='warrior')g.friendlyTick(.1);}}
function path(g,target){const queue=[[g.zoneId,[]]],seen=new Set();while(queue.length){const [id,route]=queue.shift();if(id===target)return route;if(seen.has(id))continue;seen.add(id);for(const [d,next] of Object.entries(g.zones[id].doors))if(next!=='next')queue.push([next,[...route,d]]);}throw Error('unreachable');}
test('chapter transition is gated and preserves identity, stats, loot and equipment',()=>{const g=prepared();const item=g.gear(4,2);g.bag.push(item);g.equip(item.id);const hero=g.hero,bag=g.bag,gold=hero.gold,stats={...hero.attributes};assert(g.beginChapter2());assert.equal(g.hero,hero);assert.equal(g.bag,bag);assert.equal(g.hero.gold,gold);assert.deepEqual(g.hero.attributes,stats);assert.equal(g.hero.name,'Vesper');assert.equal(g.rank(4),2);assert.equal(g.room,1);assert.equal(g.chapter,2);assert(!g.beginChapter2());assert(!new Game().beginChapter2());});
test('all rotations form seven connected sectors, reciprocal doors and exactly one exit',()=>{for(const roll of [0,.25,.5,.99]){const g=chapter('warrior',roll);assert.equal(Object.keys(g.zones).length,7);assert.equal(Object.keys(g.doors()).length,4);const opposite={up:'down',down:'up',left:'right',right:'left'};let exits=0;for(const z of Object.values(g.zones)){assert(path(g,z.id));for(const [d,next] of Object.entries(z.doors)){if(next==='next'){exits++;continue;}assert.equal(g.zones[next].doors[opposite[d]],z.id);}}assert.equal(exits,1);assert(Object.values(g.zones).some(z=>Object.keys(z.doors).length===2));}});
test('doors do not skip combat, invalid doors do nothing, annex visits preserve state',()=>{const g=chapter();g.doorCooldown=0;assert(!g.travel('up'));clear(g);g.hero.hp=55;const z=g.zones.hub;g.hero.x=z.chests[0].x;g.hero.y=z.chests[0].y;assert(g.openChest());let gold=g.hero.gold;const direction=Object.keys(g.doors()).find(d=>g.doors()[d]==='east');walk(g,direction);assert.equal(g.room,1);assert.equal(g.zoneId,'east');assert(!g.travel('invalid'));const back=Object.keys(g.doors())[0];clear(g);gold=g.hero.gold;const hp=g.hero.hp;walk(g,back);assert.equal(g.enemies.length,0);assert(g.chests[0].open);assert.equal(g.hero.gold,gold);assert.equal(g.hero.hp,hp);assert.equal(g.friendlyShots.length,0);});
test('all four populated labyrinths remain traversable and lead to the boss',()=>{const g=chapter();let defeated=0;for(let room=1;room<=4;room++){assert.equal(g.room,room);for(const z of Object.values(g.zones)){assert(z.enemies.length>=3);for(const kind of ['melee','area','caster'])assert(z.enemies.some(e=>e.kind===kind));defeated+=z.enemies.length;}for(const id of ['hub','north','east','south','west','cross','exit']){for(const d of path(g,id)){clear(g);walk(g,d);}clear(g);}const exit=Object.keys(g.doors()).find(d=>g.doors()[d]==='next');assert(exit);walk(g,exit);}assert.equal(g.chapterKills,defeated);assert.equal(g.mode,'shop');assert(g.enterBoss());assert.equal(g.boss.kind,'plague');assert(g.ally);});
test('mage and rogue projectiles damage enemies and only landed player shots heal',()=>{for(const spec of ['mage','rogue']){const g=chapter(spec);g.hero.hp=50;g.hero.face=0;g.cooldown=0;g.strike();assert.equal(g.hero.hp,50);const p=g.friendlyShots[0],e=g.enemies[0],hp=e.hp;e.x=p.x+p.vx*.05;e.y=p.y;g.friendlyTick(.05);assert(e.hp<hp);assert(g.hero.hp>50);assert.equal(g.friendlyShots.length,0);if(spec==='mage')assert(e.slow>0);}});
test('poison boss telegraphs, pools persist, venom expires and pause freezes it',()=>{const g=chapter();g.enterShop();g.enterBoss();g.boss.cycle=1;g.boss.timer=0;g.plagueTick(.01);assert.equal(g.hazards.length,3);assert(g.hazards.every(h=>!h.fired));g.hero.inv=0;g.plagueTick(1.11);assert(g.hero.poison>0);assert(g.hazards.some(h=>h.fired&&h.life>3));g.paused=true;const duration=g.hero.poison;g.tick(2);assert.equal(g.hero.poison,duration);g.paused=false;g.hazards=[];g.shots=[];g.boss.timer=99;for(let i=0;i<45;i++)g.tick(.1);assert.equal(g.hero.poison,0);});
test('ally attacks boss, never player, and can land final blow without reopening class selection',()=>{const g=chapter();g.enterShop();g.enterBoss();g.hero.hp=50;g.boss.hp=1;g.ally.x=g.boss.x-30;g.ally.y=g.boss.y;g.ally.fire=0;g.plagueTick(.01);const p=g.friendlyShots[0];assert.equal(p.owner,'ally');p.x=g.boss.x;p.y=g.boss.y;g.friendlyTick(0);assert.equal(g.hero.hp,50);assert.equal(g.mode,'reward');assert.equal(g.hero.name,'Vesper');assert(!g.specialize('Other','mage'));g.hero.x=330;g.hero.y=136;assert(g.openChest());assert.equal(g.mode,'chapter-complete');assert(!g.openChest());});
test('restart clears chapter two map, companion and poison',()=>{const g=chapter();g.enterShop();g.enterBoss();g.hero.poison=4;g.reset();assert.equal(g.chapter,1);assert.equal(g.zones,null);assert.equal(g.ally,null);assert.equal(g.hero.poison,0);assert.equal(g.hero.specialization,null);assert.equal(g.chapterKills,0);});
console.log(checks+' chapter-two integration tests passed.');
