const assert=require('node:assert/strict');
const {Game}=require('../src/engine.js');const {encode,decode}=require('../src/save.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
test('manual save round trip preserves identity, gear, health, stats and currency',()=>{const g=new Game();g.reset();g.hero.name='Vesper';g.hero.specialization='rogue';g.hero.gold=77;g.hero.hp=81;g.hero.points=4;g.hero.attributes.agility=9;g.equipped[4]=g.gear(4,2);g.bag.push(g.potion('vitality',3));const r=decode(encode(g));assert(r instanceof Game);assert.deepEqual(r.hero,g.hero);assert.deepEqual(r.equipped,g.equipped);assert.deepEqual(r.bag,g.bag);assert(r.paused);assert.equal(typeof r.strike,'function');});
test('labyrinth save retains current filtered enemies, visited annexes and opened chests',()=>{const g=new Game();g.reset();g.hero.name='Vesper';g.hero.specialization='mage';g.mode='chapter-complete';g.beginChapter2();g.enemies=[];g.chests[0].open=true;g.zones.east.visited=true;const r=decode(encode(g));assert(r);assert.equal(r.chapter,2);assert.equal(r.enemies.length,0);assert.equal(r.zones[r.zoneId].enemies,r.enemies);assert.equal(r.zones[r.zoneId].chests,r.chests);assert(r.chests[0].open);assert(r.zones.east.visited);});
test('boss save retains companion, poison and attack state',()=>{const g=new Game();g.reset();g.chapter=2;g.hero.specialization='warrior';g.enterShop();g.enterBoss();g.boss.cycle=1;g.boss.timer=0;g.plagueTick(.01);g.hero.poison=3;const r=decode(encode(g));assert(r);assert.deepEqual(r.boss,g.boss);assert.deepEqual(r.ally,g.ally);assert.deepEqual(r.hazards,g.hazards);assert.equal(r.hero.poison,3);assert(r.paused);});
test('ready and dead never overwrite a playable save',()=>{const g=new Game();assert.equal(encode(g),null);g.reset();g.mode='dead';g.hero.hp=0;assert.equal(encode(g),null);});
test('corrupt and incompatible saves fail safely',()=>{const g=new Game();g.reset();assert.equal(decode('oops'),null);const save=JSON.parse(encode(g));save.version=99;assert.equal(decode(JSON.stringify(save)),null);save.version=1;save.data.hero.attributes=null;assert.equal(decode(JSON.stringify(save)),null);assert.equal(decode(null),null);});
console.log(count+' save tests passed.');
